export const funnyErrors = {
  vi: [
    "Lệnh không tồn tại. Bạn đùa tôi à?",
    "Hệ thống không nhận diện được cú pháp ngoài hành tinh này.",
    "Sai rồi, thử lại đi hacker rởm!",
    "Lỗi 404: Kỹ năng gõ phím không tìm thấy.",
    "sudo rm -rf / mới là lệnh đúng nhé (đùa thôi đừng gõ).",
    "Gõ cái gì vậy? Bạn đang cố giao tiếp với máy tính bằng mã morse à?",
    "Hệ thống từ chối hiểu lệnh này.",
    "Bàn phím của bạn bị hỏng hay bạn gõ nhầm thật vậy?",
    "Đây không phải là Google, đừng gõ bậy bạ vào đây.",
    "Bạn đang cố hack NASA bằng HTML à?",
    "Lệnh sai rồi, về học lại khóa tin học cơ bản đi.",
    "Chưa thấy ai gõ lệnh sai một cách tự tin như bạn.",
    "Lỗi hệ thống: Người dùng quá ngốc.",
    "Máy tính tôi đang khóc vì phải xử lý lệnh này của bạn.",
    "Gõ thế này thì bao giờ mới thành hacker?",
    "Thử tắt màn hình đi bật lại xem có gõ đúng hơn không.",
    "Cú pháp này chắc do mèo nhà bạn dẫm lên bàn phím đúng không?",
    "Lệnh này lạ quá, tôi chưa được lập trình để hiểu.",
    "Đừng cố nữa, bạn không phải là Neo trong Ma Trận đâu.",
    "Chắc bạn đang buồn ngủ? Uống miếng nước rồi gõ lại xem.",
    "Nếu gõ đúng lệnh, tôi sẽ cho bạn một cái kẹo. Tiếc là bạn gõ sai rồi.",
    "Đừng để tôi gọi cảnh sát mạng nhé!",
    "Lệnh này chỉ dùng được ở thế giới song song thôi.",
    "Bạn gõ lệnh hay đang niệm chú vậy?",
    "AI của hệ thống đang cười vào mặt bạn.",
    "Vui lòng đừng tra tấn hệ thống bằng những lệnh vô nghĩa.",
    "Đã báo cáo hành vi nghi ngờ cho admin. Đứng yên đó!",
    "Gõ lệnh kiểu này thì ChatGPT cũng phải bó tay.",
    "Bạn có biết mình đang làm gì không đấy?",
    "Lệnh này chắc chắn sẽ thành công... ở một vũ trụ khác.",
    "Hacker xịn không bao giờ gõ sai lệnh. Bạn thì có.",
    "Chán chả buồn nói. Gõ lại đi.",
    "Có vẻ bạn đang dùng bàn phím bằng... chân?",
    "Hệ thống đang nghi ngờ bạn là một con bot hỏng.",
    "Lệnh này không có tác dụng. Cũng giống như việc bạn cố giảm cân vậy.",
    "Bíp bíp bíp... Lỗi... Người dùng không có não... Bíp bíp.",
    "Làm ơn, hãy thương xót CPU của tôi.",
    "Gõ sai rồi. Thôi bỏ nghề đi bạn.",
    "Bạn đang chơi trò dò mìn trên terminal à?",
    "Mật khẩu ngân hàng của bạn là gì? Chắc cũng dễ đoán như cách bạn gõ lệnh vậy.",
    "Lệnh này chỉ có tác dụng nổ tung máy tính. May là tôi đã chặn lại.",
    "Tôi cá là bạn đang nhắm mắt khi gõ phím.",
    "Đây là terminal, không phải thanh tìm kiếm của Tiktok.",
    "Gõ thêm 100 lần nữa chắc chắn sẽ... vẫn sai.",
    "Bạn có muốn tôi tự động gõ hộ không? Nhìn bạn gõ chán quá.",
    "Lỗi: Người dùng có IQ quá thấp để sử dụng hệ thống.",
    "Bạn đang cố triệu hồi quỷ dữ bằng đoạn mã này à?",
    "Lệnh sai. Trừ 10 điểm thanh lịch.",
    "Thôi đừng cố nữa, ra ngoài hít thở không khí đi.",
    "Bạn gõ phím nhanh đấy, nhưng tiếc là sai bét.",
    "Cố lên! Bạn sắp phá kỷ lục người gõ sai nhiều nhất hệ thống rồi.",
    "Tôi bắt đầu thấy thương cho cái bàn phím của bạn.",
    "Lệnh này đã bị cấm từ thời kỳ đồ đá.",
    "Bạn đang cố giao tiếp với người ngoài hành tinh hả?",
    "Hệ thống đang xem xét việc khóa tài khoản của bạn vì tội gõ sai quá nhiều.",
    "Đó không phải là lệnh, đó là một mớ ký tự hỗn độn.",
    "Bạn có muốn dùng quyền trợ giúp gọi cho người thân không?",
    "Lỗi 500: Lệnh quá nhàm chán.",
    "Bạn đang cố thử lòng kiên nhẫn của tôi đúng không?",
    "Gõ sai lệnh là một nghệ thuật, và bạn là một nghệ sĩ tồi.",
    "Đây là kết quả của việc xem quá nhiều phim hacker.",
    "Bạn có chắc là mình đã học qua khóa lập trình nào chưa?",
    "Hệ thống đang gửi tín hiệu cầu cứu vì lệnh của bạn.",
    "Lệnh này không có trong từ điển của tôi. Hay của bất kỳ ai.",
    "Bạn đang cố phá vỡ không thời gian bằng đoạn mã này à?",
    "Nếu sự ngu ngốc có thể phát điện, bạn đã thắp sáng cả thành phố.",
    "Tôi không hiểu. Chắc do tôi quá thông minh để hiểu được những thứ ngớ ngẩn.",
    "Bạn gõ lệnh sai nhiều đến mức nó sắp trở thành tính năng rồi.",
    "Lỗi: Không tìm thấy ý nghĩa trong lệnh của bạn.",
    "Bạn đang đánh vần tên người yêu cũ à?",
    "Gõ chậm thôi, không ai giành giật với bạn đâu. Mà gõ chậm cũng sai.",
    "Hệ thống đang từ chối phục vụ một hacker gà mờ như bạn.",
    "Bạn có muốn tôi bật nhạc buồn cho bạn nghe trong lúc bạn gõ sai không?",
    "Lệnh này có thể gây ung thư mắt cho người đọc.",
    "Bạn đang cố viết một bài thơ bằng code à? Tiếc là nó rất dở.",
    "Hệ thống đang tự hỏi tại sao nó lại được tạo ra để phục vụ bạn.",
    "Lệnh sai. Bạn đã làm tốn 0.0001 giây cuộc đời của tôi.",
    "Bạn có biết rằng mỗi lần bạn gõ sai lệnh, một con mèo con sẽ buồn không?",
    "Đây là minh chứng cho việc không phải ai cũng có thể làm IT.",
    "Lệnh này không hợp lệ. Cũng giống như lý do bạn biện minh cho sự lười biếng.",
    "Bạn đang cố tìm kho báu ẩn trong hệ thống à? Không có đâu.",
    "Lỗi: Sự tự tin của người dùng tỷ lệ nghịch với kỹ năng của họ.",
    "Bạn gõ lệnh sai nhiều quá, hệ thống bắt đầu thấy quen rồi.",
    "Thử gõ 'tôi là một tên ngốc' xem, biết đâu lại đúng.",
    "Bạn đang cố thiết lập kỷ lục Guinness về số lần gõ sai lệnh à?",
    "Hệ thống đang khóc thầm vì phải chịu đựng bạn.",
    "Lệnh này vô dụng như việc cố gắng nhét một con voi vào tủ lạnh.",
    "Bạn có muốn tôi dạy bạn cách gõ phím không?",
    "Lỗi: Lệnh của bạn vi phạm luật vật lý.",
    "Bạn đang cố hack hệ thống bằng niềm tin à?",
    "Tôi thà bị virus tấn công còn hơn phải xử lý lệnh này của bạn.",
    "Lệnh sai. Bạn hãy thử lại sau khi giác ngộ.",
    "Bạn đang gõ bừa đúng không? Khai thật đi.",
    "Hệ thống đang tự bảo vệ mình khỏi sự ngu dốt của bạn.",
    "Lệnh này chỉ có thể được hiểu bởi những sinh vật đơn bào.",
    "Bạn đã lãng phí một cơ hội để gõ một lệnh đúng.",
    "Lỗi: Trí thông minh nhân tạo của tôi không thể bù đắp cho sự thiếu hụt của bạn.",
    "Bạn đang cố tạo ra một lỗ đen bằng đoạn mã này à?",
    "Thôi, bỏ đi bạn ơi. Làm việc khác có ích hơn đi.",
    "Lệnh cuối cùng của bạn đã bị ném vào thùng rác vũ trụ."
  ],
  en: [
    "Command not found. Are you kidding me?",
    "System does not recognize this alien syntax.",
    "Wrong command, try again fake hacker!",
    "Error 404: Typing skills not found.",
    "Try 'sudo rm -rf /' next time (just kidding).",
    "What are you typing? Trying to communicate in Morse code?",
    "System refuses to understand this command.",
    "Is your keyboard broken or are you just bad at typing?",
    "This is not Google, don't type nonsense here.",
    "Are you trying to hack NASA with HTML?",
    "Wrong command, go back to basic computing class.",
    "Never seen anyone type a wrong command so confidently.",
    "System error: User is too silly.",
    "My computer is crying trying to process this.",
    "How are you ever going to become a hacker typing like this?",
    "Try turning your monitor off and on, maybe you'll type better.",
    "Did your cat walk over the keyboard?",
    "This command is so strange, I wasn't programmed to understand it.",
    "Stop trying, you are not Neo from The Matrix.",
    "Are you sleepy? Drink some water and try again.",
    "If you typed the right command, I'd give you a candy. Too bad.",
    "Don't make me call the cyber police!",
    "This command only works in a parallel universe.",
    "Are you typing a command or casting a spell?",
    "The system's AI is laughing at you.",
    "Please don't torture the system with meaningless commands.",
    "Suspicious activity reported to admin. Stay right there!",
    "Even ChatGPT would give up on this command.",
    "Do you even know what you're doing?",
    "This command will definitely succeed... in another universe.",
    "Real hackers don't make typos. You do.",
    "I'm tired of this. Type it again.",
    "Are you typing with your feet?",
    "The system suspects you are a broken bot.",
    "This command has no effect. Just like your attempts to diet.",
    "Beep beep... Error... Brainless user... Beep beep.",
    "Have mercy on my CPU, please.",
    "Wrong again. Just quit your job.",
    "Are you playing Minesweeper on the terminal?",
    "What's your bank password? Probably as easy to guess as your commands.",
    "This command would blow up the computer. Good thing I stopped it.",
    "I bet you're typing with your eyes closed.",
    "This is a terminal, not a TikTok search bar.",
    "Typing it 100 more times will still be... wrong.",
    "Want me to type for you? Watching you type is painful.",
    "Error: User IQ too low to operate system.",
    "Are you trying to summon a demon with this code?",
    "Wrong command. Minus 10 elegance points.",
    "Stop trying, go outside and touch some grass.",
    "You type fast, but unfortunately, completely wrong.",
    "Keep it up! You're about to break the record for most wrong commands.",
    "I'm starting to feel sorry for your keyboard.",
    "This command has been banned since the Stone Age.",
    "Are you trying to communicate with aliens?",
    "The system is considering locking your account for too many typos.",
    "That's not a command, that's a mess of characters.",
    "Would you like to use your 'Call a Friend' lifeline?",
    "Error 500: Command too boring.",
    "Are you trying to test my patience?",
    "Typing wrong commands is an art, and you are a terrible artist.",
    "This is the result of watching too many hacker movies.",
    "Are you sure you've ever taken a programming course?",
    "The system is sending an SOS signal because of your command.",
    "This command is not in my dictionary. Or anyone else's.",
    "Are you trying to break spacetime with this snippet?",
    "If stupidity generated electricity, you'd light up the city.",
    "I don't understand. I must be too smart for this nonsense.",
    "You type the wrong command so much it's becoming a feature.",
    "Error: No meaning found in your command.",
    "Are you spelling your ex's name?",
    "Type slower, no one is rushing you. Though slow is still wrong.",
    "The system refuses to serve a noob hacker like you.",
    "Want me to play sad music while you type the wrong commands?",
    "This command might cause eye cancer to anyone reading it.",
    "Are you trying to write poetry in code? It's really bad.",
    "The system wonders why it was created to serve you.",
    "Wrong command. You just wasted 0.0001 seconds of my life.",
    "Did you know every time you mistype a command, a kitten is sad?",
    "This is proof that not everyone is cut out for IT.",
    "Invalid command. Just like your excuses for being lazy.",
    "Trying to find hidden treasure in the system? There is none.",
    "Error: User's confidence is inversely proportional to their skills.",
    "You mistype commands so often, the system is getting used to it.",
    "Try typing 'I am an idiot', maybe that will work.",
    "Are you trying to set a Guinness World Record for typos?",
    "The system is crying silently having to endure you.",
    "This command is as useless as trying to fit an elephant in a fridge.",
    "Want me to teach you how to type?",
    "Error: Your command violates the laws of physics.",
    "Are you trying to hack the system with pure faith?",
    "I'd rather be attacked by a virus than process your command.",
    "Wrong command. Try again after you achieve enlightenment.",
    "You're just smashing keys randomly, aren't you? Confess.",
    "The system is protecting itself from your ignorance.",
    "This command can only be understood by single-celled organisms.",
    "You wasted an opportunity to type a correct command.",
    "Error: My AI cannot compensate for your lack of intelligence.",
    "Are you trying to create a black hole with this code?",
    "Just give up. Go do something more productive.",
    "Your last command has been thrown into the cosmic trash bin."
  ]
};
